version: "3"

services:
  mysql:
    image: mysql:8.0
    container_name: bioprint-db
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./mysql-volume:/var/lib/mysql
      - ./latest_data:/docker-entrypoint-initdb.d
    ports:
      - 3307:3306